name: Deploy to OVH VPS

on:
  push:
    branches:
      - main # Déclenche la pipeline sur un push dans la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to OVH VPS
        run: |
          rsync -avz --delete --exclude '.git' ./ marclag@${{ secrets.SERVER_IP }}:/home/marclag/ulysse

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
